apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.project.id }}-{{ .Chart.Name }}
spec:
  selector:
    app: {{ .Values.project.id }}-{{ .Chart.Name }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: "{{ .Values.service.port }}"
      protocol: TCP
    - port: {{ .Values.service.apiPort }}
      targetPort: {{ .Values.service.apiPort }}
      name: "{{ .Values.service.apiPort }}"
      protocol: TCP
